name: Test

on: [push]

jobs:
  test:
    name: Test (${{ matrix.os }} / node ${{ matrix.node }})
    runs-on: ${{ matrix.os }}
    continue-on-error: ${{ matrix.experimental }}

    strategy:
      matrix:
        os: [ubuntu-latest]
        node: [16]
        experimental: [false]
        include:
          - os: windows-latest
            node: 16
            experimental: true

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set as path var var
        run: |
          echo "{{GITHUB_WORKSPACE}}/src/bin" >> $GITHUB_PATH

      - name: Test command in folder
        run: |
          cd "{{GITHUB_WORKSPACE}}/example"
          gh-test

      - name: Test command with flag
        shell: bash
        run: |
          cd $RUNNER_TEMP
          gh-test --dir=$RUNNER_TEMP/test-project
